export const categoryList = [
  "Select category",
  "All Category",
  "Accessories",
  "Air Conditioners",
  "Cameras",
  "Geysers",
  "Fans",
  "Grooming",
  "Headphones & Earphones",
  "Home Theaters & Soundbars",
  "Kitchen Appliances",
  "Laptops",
  "Coolers",
  "Microwaves",
  "Mobiles",
  "Refrigerators",
  "Speakers & Media Players",
  "Tablets",
  "Televisions",
  "Washing Machines",
  "Water Purifiers",
  "Wearables",
];

export const brandList = [
  "Select brand",
  "All Brands",
  "PHILIPS",
  "SAMSUNG",
  "oppo",
  "Lenovo",
  "hp",
  "Haier",
  "DELL",
  "croma",
  "mi",
  "vivo",
  "JBL",
  "BOSE",
  "Another",
];
